export const randomPrompts = [
	"sleek black sports car roared down the highway.",
	"fluffy white kitten purred contentedly in its owner's lap.",
	"giant blue whale swam gracefully through the ocean.",
	"shiny silver key unlocked the door to the treasure chest.",
	"sticky green slime oozed out of the jar.",
	"rusty old bicycle leaned against the fence.",
	"glittering gold necklace sparkled in the sunlight.",
	"soft pink rose petals scattered across the table.",
	"furry brown teddy bear sat on the shelf.",
	"vibrant orange pumpkin sat on the doorstep.",
	"smoky grey fog obscured the view.",
	"tiny yellow bird chirped happily in the tree.",
	"massive red brick building towered over the city.",
	"smooth green apple tasted crisp and juicy.",
	"sharp silver knife sliced through the steak.",
	"delicate purple orchid bloomed in the window.",
	"rough grey stone lay on the beach.",
	"fluffy blue cloud floated lazily across the sky.",
	"icy cold water chilled my bones.",
	"sparkling diamond ring caught the light and glittered.",
	"ancient wooden chest was filled with treasure.",
	"sour green lemon puckered my lips.",
	"silky black nightgown felt soft against my skin.",
	"bright yellow sunflower turned its face towards the sun.",
	"sticky red jam dripped down the side of the toast.",
	"crisp green lettuce was fresh from the garden.",
	"shiny black patent leather shoes gleamed in the light.",
	"fluffy white cloud resembled a cotton ball.",
	"heavy metal barbell weighed down his arms.",
	"pale blue sky stretched endlessly above us.",
	"smooth silver dolphin glided through the water.",
	"spicy red salsa gave a kick to the dish.",
	"beautiful white swan gracefully swam in the pond.",
	"sharp black thorns pricked my finger.",
	"bright orange traffic cone warned of roadwork ahead.",
	"glittering red sequins sparkled on the dress.",
	"soft brown leather couch was perfect for lounging.",
	"sticky pink cotton candy melted in my mouth.",
	"cold grey stone statue stood in the park.",
	"beautiful purple amethyst caught the light and shone.",
	"bright green grass tickled my feet.",
	"sleek silver laptop was perfect for work.",
	"bright red fire truck sped down the street.",
	"crisp brown toast smelled delicious.",
	"beautiful yellow butterfly fluttered in the garden.",
	"heavy black safe held the valuables securely.",
	"soft blue blanket was warm and cozy.",
	"rough brown bark of the tree was textured.",
	"beautiful white seashell was smooth and delicate.",
	"vibrant green leaves rustled in the breeze.",
	"sweet red cherry popped in my mouth.",
	"sleek black cat slinked through the shadows.",
	"fluffy white snow covered the ground.",
	"shiny silver spoon gleamed in the light.",
	"sticky brown caramel dripped from the candy apple.",
	"rusty old car creaked down the road.",
	"glittering blue ocean stretched out before us.",
	"soft pink baby blanket was soft to the touch.",
	"furry brown squirrel scampered up the tree.",
	"vibrant orange sunset painted the sky.",
	"smoky grey charcoal added depth to the drawing.",
	"delicate purple lavender flowers filled the air with their scent.",
	"rough brown sandpaper smoothed out the rough edges.",
	"fluffy white marshmallows melted in the hot cocoa.",
	"sleek black pen glided across the paper effortlessly.",
	"sticky red lipstick left a mark on the glass.",
	"rusty old nail was stuck in the wood.",
	"glittering silver tiara adorned the princess's head.",
	"soft pink cotton candy reminded me of childhood.",
	"furry brown dog wagged its tail excitedly.",
	"vibrant orange basketball bounced on the court.",
	"smoky grey charcoal grill infused the meat with flavor.",
	"tiny green gecko scurried up the wall.",
	"shiny black piano gleamed in the spotlight.",
	"fluffy white clouds resembled cotton candy in the sky.",
	"smooth blue ocean waves lapped against the shore.",
	"sharp yellow pencil drew precise lines.",
	"delicate white lace added a touch of elegance to the dress.",
	"rough grey sidewalk was bumpy to walk on.",
	"glittering green emerald caught the light and shimmered.",
	"soft purple lavender lotion moisturized my skin.",
	"furry black and white panda chewed on bamboo.",
	"vibrant pink tulip stood out among the other flowers.",
	"smoky black coffee woke me up in the morning.",
	"slippery orange peel caused me to slip and fall.",
	"shiny silver trophy was a symbol of victory.",
	"fluffy brown teddy bear comforted me in times of need.",
	"cold blue ice cube cooled down my drink.",
	"smooth red apple was juicy and sweet.",
	"sharp white teeth bit down on the crunchy carrot.",
	"delicate pink cherry blossom petals fell gently to the ground.",
	"rough brown paper bag held the groceries.",
	"glittering blue sapphire caught the eye of the beholder.",
	"soft yellow chick chirped in its nest.",
	"furry grey cat curled up on the windowsill.",
	"vibrant green grasshopper hopped around the garden.",
	"smoky black leather jacket looked stylish and cool.",
	"shiny golden trophy shone in the light.",
	"fluffy white sheep grazed in the meadow.",
	"slippery pink soap made the shower a hazard.",
	"smooth black leather wallet held my money and cards.",
]